### ISSUE TITLE
[Bug]: Soul Shard Crafting REI Not showing

### ISSUE THREAD

**Issue by manmaed** [CreeperHost/SoulShards#15]
REI not showing how to do the multi block
Minecraft: 1.19.2
Forge: 43.2.21
PolyLib: 1900.0.2-build.73
SoulShards: 1.3.4

![](https://ss.manmaed.net/1691179644.png)

**Comment by gigabit101** [comment]
Yup, This is a known issue with the render being for JEI and REI not rendering it

**Comment by gigabit101** [comment]
Fixed in 1.3.6
