### ISSUE TITLE
The gif on the curseforge page is gone

### ISSUE THREAD

**Issue by mvl666Darkrio** [CreeperHost/SoulShards#16]
Exactly what the title says. The gif showing the method to obtain a shard is missing, due to gfycat going permanently down.

**Comment by Kadah** [comment]
For anybody looking for what the structure is, this is it:

4 obsidian, 4 quartz block, glowstone.

![image](https://github.com/CreeperHost/SoulShards/assets/751209/25ba56dc-43ac-4c3c-9e3e-79baf6577e39)

**Comment by gigabit101** [comment]
It's in JEI but I do like your layout, Will get the image on Curse updated

**Comment by gigabit101** [comment]
The gif is now back on the page
