### ISSUE TITLE
Bug? 'allowShardCombination"

### ISSUE THREAD

**Issue by YukiNoHana-0** [CreeperHost/SoulShards#18]
Ive check the config soulshards.json and there is a line

>     "allowShardCombination": true,

Correct me if I'm wrong, does this mean that i can combine two shards of the same entity and it will become one?
For example i have a shard of evoker which has a 10 souls and another shard of evoker which has 20 souls, does the     "allowShardCombination": true, allows them to be combined as one making a shard with 30 souls of evoker?

If this was this config functionality, Im sorry its not working, when i put the 2 shards on the crafting grid is not getting combined. (if this is a feature).

If this was not the config meant, then can i have a suggestion to combine same shard that has the same entity?

**Comment by gigabit101** [comment]
use an anvil
