### ISSUE TITLE
Mod does not respect block spawn rules or Forge CheckSpawn event

### ISSUE THREAD

**Issue by robotgryphon** [CreeperHost/SoulShards#4]
The spawner does not appear to check Forge's `LivingSpawnEvent.CheckSpawn` event, nor does it check if blocks overrode `isValidSpawn`. Looks like the check appears around the following code area:

https://github.com/CreeperHost/SoulShards/blob/d4103a16a0d955dd92a94b89d884b8e52c01a6d9/src/main/java/net/creeperhost/soulshardsrespawn/block/TileEntitySoulCage.java#L112-L113

This is causing several mob spawning issues with Compact Machines where enderman/shulkers are outside machine rooms. Adding these event checks would mean other mods can guard against spawns without specific compat code.

**Comment by perlguy** [comment]
Would this also be why soul cages stop spawning when players move more than 128 blocks away, even when using chunk loaders? (tested with both FTB Chunks and Chunk Loaders).

Playing Direwolf20 1.18 pack, and everything seems ok except when I move beyond 128 blocks from the spawner, even for a tier 5.

**Comment by perlguy** [comment]
pretty sure my issue is not specific to soul shards.  Seeing the same thing with dreadful dirt and agitators.  if it is related, then it's some odd interaction between forge and 1.18 spawning mechanics.  Opened an FTB issue here:

https://github.com/FTBTeam/FTB-Modpack-Issues/issues/922

**Comment by gigabit101** [comment]
> Would this also be why soul cages stop spawning when players move more than 128 blocks away, even when using chunk loaders? (tested with both FTB Chunks and Chunk Loaders).
> 
> Playing Direwolf20 1.18 pack, and everything seems ok except when I move beyond 128 blocks from the spawner, even for a tier 5.

This is a different issue and will need to be opened as a new issue however since we don't check if a player is nearby in higher tier soul shards this sounds like a chunk loading issue

**Comment by gigabit101** [comment]
> The spawner does not appear to check Forge's `LivingSpawnEvent.CheckSpawn` event, nor does it check if blocks overrode `isValidSpawn`. Looks like the check appears around the following code area:
> 
> https://github.com/CreeperHost/SoulShards/blob/d4103a16a0d955dd92a94b89d884b8e52c01a6d9/src/main/java/net/creeperhost/soulshardsrespawn/block/TileEntitySoulCage.java#L112-L113
> 
> This is causing several mob spawning issues with Compact Machines where enderman/shulkers are outside machine rooms. Adding these event checks would mean other mods can guard against spawns without specific compat code.

I'm still trying to figure out a good way to implement this, The entire point of a T5 shard is that it ignores spawn conditions, Still trying to figure out how to do this without breaking the T5 shard

**Comment by mtbrenner** [comment]
Might be the reason why a cow shard L1 only spawns cows when it is dark which is counterintuitive.

**Comment by gigabit101** [comment]
This should be fixed in later builds of the mod
