### ISSUE TITLE
Cannot create Soul Shard

### ISSUE THREAD

**Issue by Raidobw2** [CreeperHost/SoulShards#5]
Not sure what is happening, but I'm unable to create a Soul Shard in singleplayer (have not tested multiplayer). Here's my modlist:
![image](https://user-images.githubusercontent.com/17010632/170919393-defef227-4b02-478c-9383-eebf347892e4.png)
`architectury-4.4.68.jar`
`soulshards-1.18.2-1.2.2.jar`
`polylib-forge-1801.0.2-build.13.jar`

The pattern I tried (and using normal quartz blocks too, this is the picture with quartz pillars):
![image](https://user-images.githubusercontent.com/17010632/170919446-7b4c5a36-e886-4a3d-97e5-d5f41337bb85.png)

I tried downgrading Architectury a few versions, that didn't work too. I also tried to make a multiblock.json file in the root of a datapack (data/multiblock.json) as seen in the files of this repo, but it didn't work either. I tried standing on top and inside the glowstone block as well (using pistons).

I am right clicking the glowstone block in the picture with a diamond
Forge `40.1.25`
Minecraft `1.18.2`

**Comment by gigabit101** [comment]
Wrong quartz blocks...

**Comment by gigabit101** [comment]
Works for me in dev/test instance with just it + deps installed and in the Forgecraft instance.
https://ss.gigabit101.net/javaw_lgM5pU8Oj7.gif

**Comment by Raidobw2** [comment]
Do I have to use Smooth Quartz? I'll retry again with it in a bit

**Comment by gigabit101** [comment]
You need to use Block of Quartz

**Comment by Raidobw2** [comment]
Tried with block of quartz and it works now, apologies for the report and thanks for your help!

**Comment by gigabit101** [comment]
Block of quartz
