### ISSUE TITLE
[1.18.2] Suggetion: More Localisation Support

### ISSUE THREAD

**Issue by StarskyXIII** [CreeperHost/SoulShards#9]
Currently, I am playing on FTB Stoneblock 3, and I want to translate all mods for my bad in English friends.
But it seems JEI information and category can't be translated.
![image](https://user-images.githubusercontent.com/71606873/199837137-20e27c1a-5f69-4a98-baa0-eb3a68fb1211.png)

And I can't find these texts ingame, had they beem removed ?
![missing](https://user-images.githubusercontent.com/71606873/199843451-633e2bb5-a2ef-42a4-95e3-d63a1bb3430b.png)

**Comment by gigabit101** [comment]
This should be fixed in later builds of the mod
